var JejuAccData = [
  {
    "id": "1",
    "year": "2017",
    "month": "2",
    "date": "17",
    "accScale": "부상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "2",
    "year": "2017",
    "month": "2",
    "date": "20",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "3",
    "year": "2017",
    "month": "2",
    "date": "17",
    "accScale": "중상사고",
    "carType": "이륜",
    "accType1": "일직선사고",
    "accType2": "차대차",
    "accType3": "추돌(진행중)"
  },
  {
    "id": "4",
    "year": "2017",
    "month": "3",
    "date": "6",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "5",
    "year": "2017",
    "month": "5",
    "date": "1",
    "accScale": "중상사고",
    "carType": "승합",
    "accType1": "일직선사고",
    "accType2": "차대차",
    "accType3": "추돌(진행중)"
  },
  {
    "id": "6",
    "year": "2017",
    "month": "10",
    "date": "26",
    "accScale": "중상사고",
    "carType": "이륜",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "7",
    "year": "2017",
    "month": "11",
    "date": "20",
    "accScale": "중상사고",
    "carType": "승합",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "8",
    "year": "2017",
    "month": "11",
    "date": "28",
    "accScale": "중상사고",
    "carType": "이륜",
    "accType1": "기타사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "9",
    "year": "2017",
    "month": "12",
    "date": "14",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "10",
    "year": "2018",
    "month": "3",
    "date": "19",
    "accScale": "중상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "11",
    "year": "2018",
    "month": "4",
    "date": "19",
    "accScale": "중상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "12",
    "year": "2018",
    "month": "6",
    "date": "11",
    "accScale": "중상사고",
    "carType": "승합",
    "accType1": "기타사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "13",
    "year": "2018",
    "month": "6",
    "date": "23",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "14",
    "year": "2018",
    "month": "7",
    "date": "25",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "일직선사고",
    "accType2": "차대차",
    "accType3": "추돌(진행중)"
  },
  {
    "id": "15",
    "year": "2018",
    "month": "8",
    "date": "29",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "16",
    "year": "2018",
    "month": "9",
    "date": "30",
    "accScale": "중상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "17",
    "year": "2018",
    "month": "9",
    "date": "22",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "18",
    "year": "2018",
    "month": "9",
    "date": "22",
    "accScale": "부상사고",
    "carType": "이륜",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "19",
    "year": "2018",
    "month": "10",
    "date": "16",
    "accScale": "경상사고",
    "carType": "이륜",
    "accType1": "기타사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "20",
    "year": "2018",
    "month": "11",
    "date": "20",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "21",
    "year": "2018",
    "month": "11",
    "date": "21",
    "accScale": "경상사고",
    "carType": "화물",
    "accType1": "기타사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "22",
    "year": "2018",
    "month": "11",
    "date": "11",
    "accScale": "중상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "23",
    "year": "2018",
    "month": "12",
    "date": "23",
    "accScale": "중상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "24",
    "year": "2018",
    "month": "12",
    "date": "22",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "25",
    "year": "2019",
    "month": "1",
    "date": "19",
    "accScale": "중상사고",
    "carType": "화물",
    "accType1": "기타사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "26",
    "year": "2019",
    "month": "1",
    "date": "10",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "27",
    "year": "2019",
    "month": "1",
    "date": "23",
    "accScale": "부상사고",
    "carType": "이륜",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "28",
    "year": "2019",
    "month": "2",
    "date": "10",
    "accScale": "부상사고",
    "carType": "기타",
    "accType1": "단독사고",
    "accType2": "차량단독",
    "accType3": "공작물추돌"
  },
  {
    "id": "29",
    "year": "2019",
    "month": "4",
    "date": "5",
    "accScale": "중상사고",
    "carType": "이륜",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "30",
    "year": "2019",
    "month": "6",
    "date": "6",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "31",
    "year": "2019",
    "month": "6",
    "date": "21",
    "accScale": "중상사고",
    "carType": "화물",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "32",
    "year": "2019",
    "month": "6",
    "date": "19",
    "accScale": "경상사고",
    "carType": "이륜",
    "accType1": "기타사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "33",
    "year": "2019",
    "month": "7",
    "date": "25",
    "accScale": "부상사고",
    "carType": "원동기",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "34",
    "year": "2019",
    "month": "7",
    "date": "9",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "기타사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "35",
    "year": "2019",
    "month": "7",
    "date": "10",
    "accScale": "중상사고",
    "carType": "이륜",
    "accType1": "기타사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "36",
    "year": "2019",
    "month": "10",
    "date": "2",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "37",
    "year": "2019",
    "month": "11",
    "date": "30",
    "accScale": "경상사고",
    "carType": "승용",
    "accType1": "기타사고",
    "accType2": "차대차",
    "accType3": "차대차-기타"
  },
  {
    "id": "38",
    "year": "2019",
    "month": "12",
    "date": "9",
    "accScale": "중상사고",
    "carType": "이륜",
    "accType1": "진입회전사고",
    "accType2": "차대차",
    "accType3": "측면직각충돌"
  },
  {
    "id": "39",
    "year": "2019",
    "month": "12",
    "date": "30",
    "accScale": "중상사고",
    "carType": "보행자",
    "accType1": "진입회전사고",
    "accType2": "차대사람",
    "accType3": "차대사람-기타"
  }
];